sudo: required
language: node_js
env:
  - CXX="g++-4.8"

node_js:
  - 'stable'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

branches:
  only:
  - master

install:
  - npm install

script:
  - npm run build

cache:
  directories:
    - node_modules

git:
  depth: 1

branches:
  only:
    - /.*/
