language: node_js

node_js:
  - 'stable'

sudo: false

branches:
  only:
  - master

install:
  - npm install

script:
  - npm build
  - npm start

cache:
  directories:
    - node_modules

git:
  depth: 1